version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      POSTGRES_USER: user
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./pg-initdb.d:/docker-entrypoint-initdb.d
      
  mongodb: 
    image: mongo 
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
       
  neo4j:
    image: neo4j/neo4j-experimental:4.0.0-rc01   # not release yet.
    environment:
      - "NEO4J_AUTH=neo4j/test"
      - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes"
    ports:
      - 7687:7687 
      - 7474:7474 