version: '3.3' # specify docker-compose version

# Define the services/containers to be run
services:

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
      POSTGRES_USER: user
    volumes:
      - ./data/postgresql:/var/lib/postgresql
      - ./pg-initdb.d:/docker-entrypoint-initdb.d
      
  mongodb: 
    image: mongo 
    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
       
  neo4j:
    image: neo4j:4.0   # 4.0
    environment:
      - "NEO4J_AUTH=neo4j/test" # disable authentication by passing --env=NEO4J_AUTH=none
      - "SECURE_FILE_PERMISSIONS=yes" # To enforce stricter file permissions checking 
    #  - "NEO4J_ACCEPT_LICENSE_AGREEMENT=yes" # required for enterprise editon: neo4j:4.0.0-enterprise
    ports:
      - 7687:7687 
      - 7474:7474 