spring:
  h2:
    console:
      #http://localhost:8080/h2-console
      enabled: true
  r2dbc:
#    url: r2dbc:postgresql://localhost/test
#    username: user
#    password: password
    initialization-mode: always
    url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    name: sa
    password:
  liquibase:
    enabled: true
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1

logging:
  level:
    org.springframework.data.r2dbc: DEBUG